---
- hosts: localhost
  tasks:
    - shell: kubeadm token create --print-join-command
      register: results
    - debug:
        var: results.stdout
    - set_fact:
        join_cmd: "{{ results.stdout }}"

- hosts: workers
  vars:
    join_cmd: {{ hostvars[groups['localhost']['join_cmd'] }}
  tasks:
    - name: add kubernetes repo
      copy:
        src: virt7-kubernetes-110-release.repo
        dest: /etc/yum.repos.d/virt7-kubernetes-110-release.repo
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - kubernetes-kubeadm
    - name: activate docker
      systemd:
        name: docker
        enabled: yes
        state: started
    - name: fix selinux perms
      script: fix_selinux_perms.sh
    - name: reset kubernetes
      shell: kubeadm reset
    - name: start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started
    - name: join cluster
      shell: {{ join_cmd }}
